services:
  site:
    container_name: nnsite
    build:
      context: .
      dockerfile: apps/site/Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - notes
    depends_on:
      api:
        condition: service_healthy

  api:
    container_name: nnapi
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "8080"
    networks:
      - notes
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: nndb
    image: postgres:18-trixie
    restart: unless-stopped
    expose:
      - "5432" # Internal only by default
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - notes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  notes:
    driver: bridge
